/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 4f35b84823b843790874c39d19267ca6)
// Runtime types generated with workerd@1.20260504.1 2025-10-08 nodejs_compat
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		R2_BUCKET: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VALUE_FROM_CLOUDFLARE">> {}
}

// Begin runtime types
// (Runtime types remain the same as provided)
